FROM ruby:2.4.2-alpine3.6

RUN set -ex \
  \
  && apk add --no-cache --virtual .fpm-builddeps \
  make \
  gcc \
  musl-dev \
  \
  && gem install fpm \
  && apk del .fpm-builddeps \
  && apk add --no-cache rpm



